#!/usr/bin/env zsh

#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#---- ---- ----

source ~/.zprezto/runcoms/zshenv.elasticsearch
source ~/.zprezto/runcoms/zshenv.logstash
source ~/.zprezto/runcoms/zshenv.nomad
source ~/.zprezto/runcoms/zshenv.zookeeper
